.TH COMMONVOICE-STATUS 1 "February 2026" "commonvoice-status" "User Commands"
.SH NAME
commonvoice-status \- Mozilla Common Voice contribution status viewer
.SH SYNOPSIS
.B commonvoice-status
.SH DESCRIPTION
Mozilla Common Voice contribution status viewer.
.SH AUTHOR
Daniel Nylander <daniel@danielnylander.se>
